### ISSUE TITLE
Add windows/linux/mac builds

### ISSUE THREAD

**Issue by arthur-parmentier** [zamgi/m3u8#2]
Could you add a build folder with different OS builds?

thanks in advance!

**Comment by zamgi** [comment]
I do not know how to do this because I use only Windows.
in addition, part of the code will be built only under Windows.

**Comment by arthur-parmentier** [comment]
Could you then upload only the windows build? That would be very helpful

**Comment by zamgi** [comment]
give me your e-mail - I will send you
