### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by zackmark29** [zamgi/m3u8#3]
Hi. I always failed to build the project.
Could you please give us the final build and extension?
This is really a good tool

**Comment by zamgi** [comment]
Give me your email - i send you.

**Comment by zackmark29** [comment]
> Give me your email - i send you.

Wow really? here's my email: 
zackmark291993@gmail.com

Thank you so much.
I'm excited to use it

**Comment by zamgi** [comment]
...
