### ISSUE TITLE
How to make one console app to use this repo for Windows 10?

### ISSUE THREAD

**Issue by zydjohnHotmail** [zamgi/m3u8#7]
Hello:
I found your repo, it looks very good one.  I want to make one console app using this repo.
I am using Visual Studio 2019 (Version 16.11.5), I tried to download the source code and unzip it, trying to build the project.
But I saw the error for “MainForm.cs” in WinFrom designer: 
Could not find type "System.Windows.Forms.ButtonWithFocusCues".  Please make sure that the assembly that contains this type is referenced. If this type is a part of your development project, make sure that the project has been successfully built using settings for your current platform or Any CPU.
The variable 'outputFileNameClearButton' is either undeclared or was never assigned.
The variable 'm3u8FileWholeLoadAndSaveButton' is either underclared or was never assigned.
The variable 'm3u8FileTextContentLoadButton' is either underclared or was never assigned.

I don’t know how to fix this, but do you have a NUGET package for this repo, so I can easily install it in C#?
I want to create one console app targeting .NET 5.0 for Windows 10 (Version 21H1).
Thanks,

**Comment by zamgi** [comment]
hey.

1)
I am getting a repo into a clean machine and make build for solution (from VS) - everything ok. 
Class"System.Windows.Forms.ButtonWithFocusCues" location here: 
   '.\m3u8\m3u8.download.manager\WinForms\UI\UC\ButtonWithFocusCues.cs'
2) 
 For make one console app you doesn't need build all solution - you need build only project 'm3u8.console.app' (in her not exists any refs to "System.Windows.Forms.ButtonWithFocusCues" class)

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I have done the following:
I created one new console app target .NET 5.0 (AnyCPU), I added 3 classes:
m3u8.client.cs
m3u8.client.factory.cs
m3u8_processor.cs
And one App.config file with all the contents from your project.
In Program.cs, I copied and pasted all the code in your Program.cs from 'm3u8.console.app'

I had minor error: VS2019 complains not knowing ConfigurationManager, but give advice to install latest version of System.Configuration.ConfigurationManager, like this:
PM> Install-Package System.Configuration.ConfigurationManager -Version 5.0.0
After adding this NUGET package, my code got complied, but when I run my code, I got the following run time error:

ERROR: System.NotSupportedException: The requested security protocol is not supported.
   at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
   at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
   at m3u8.Program.Main(String[] args) in C:\EditVideos\M3U8\m3u8\m3u8\Program.cs:line 468


[.....finita fusking comedy..…]

Let me know how I can fix this issue.  I think the security protocol should be supported by System.Net name space, right?

By the way, I found you have private static class v1, private static class v2, private static class v3
Let me know what is the difference between v1, v2 and v3.  Which one I should use? (If I have 3 version of M3U8 links, like ordinary resolution link, 720P resolution link and 1080P resolution  link)
Thanks,

**Comment by zamgi** [comment]
Im add .net5.0 console app example. Try re-get repo again.

**Comment by zydjohnHotmail** [comment]
Hello:
I have done the following:
Copy all the files from 'm3u8.console.app_2':
m3u8.client.cs
m3u8.client.factory.cs
m3u8_processor.cs
And one App.config file with all the contents from your project.
In Program.cs, I copied and pasted all the code in your Program.cs from 'm3u8.console.app_2' 
Add the following Nuget packages:
PM> Install-Package System.Configuration.ConfigurationManager -Version 5.0.0 
PM>Install-Package System.Text.Encoding.CodePages -Version 5.0.0

But when I run my code, I got the following run time errors:
ERROR: System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize
 ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.net. (C:\EditVideos\M3U8\m3u8\m3u8\bin\Debug\net5.0\m3u8.dll.config line 15)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at m3u8.Program.Main(String[] args) in C:\EditVideos\M3U8\m3u8\m3u8\Program.cs:line 476


[.....finita fusking comedy..…]

The following is the m3u8.dll.config file:
<?xml version="1.0" encoding="utf-8"?>
<configuration>

  <appSettings>
    <add key="M3U8_FILE_URL"   value="http://185.38.12.40/sec/1516385824/3335383362420723ca8d40547d6835cf803a95f5c4e15ed6/ivs/0d/e8/0af8f8c8901c.mp4/hls/tracks-3,4/index.m3u8"/>
    <add key="OUTPUT_FILE_DIR" value="E:\"/>
    <add key="OUTPUT_FILE_EXT" value=".avi"/>
  </appSettings>

  <runtime>
    <gcServer     enabled="true"  />
    <gcConcurrent enabled="false" />
  </runtime>

  <system.net>
    <connectionManagement>
      <add address="*" maxconnection="1024" />
    </connectionManagement>
  </system.net>

  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/>
  </startup>

</configuration>

It seems the issue is:
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/>
  </startup>

How to generate a new file for .NET 5.0?
Thanks,

**Comment by zydjohnHotmail** [comment]
Hello:
Sorry, I made a mistake, I didn’t change App.Config file, now I change it, and it is working now.
However, I need the following features:
1) Can I delete the App.Config file? As I need to download quite a number of live M3U8 files (MP4 format) every day, from 10 to 100 per day.  But I don’t know the M3U8 links before I begin download, I can detect those M3U8 links using JavaScript from some web site.  Anyway, have to get rid of App.Config.
2) I need to download all live M3U8 links in background, not showing any debug information, but I need to know when each live M3U8 download finishes.
How I can do this?
Thanks,

**Comment by zamgi** [comment]
1. yes, you can delete the App.Config file. (To do this, you need to remove from the code everything that uses App.Config/System.Configuration.ConfigurationManager)
2. I don't know if it is possible to download live M3U8 links (may be this is different format ?) - give me a anyone  live M3U8 links - i try this... 
(for not showing any debug information - you need search in code places with output to console....)

**Comment by zydjohnHotmail** [comment]
Hello:
You can try this LIVE M3U8 link to see if it works:
https://video1.maxline.by:444/o1/stream05/playlist.m3u8

**Comment by zamgi** [comment]
I can test this link - access denied, but I think some live links may contain other links to parts of the real video ... its didn't need that for my necessity

**Comment by zydjohnHotmail** [comment]
Hello:
Where are you launching the program? I can visit the link from Spain.  But from US, the link is not working.  I will try to find some other live M3U8 links for you to test.

**Comment by zydjohnHotmail** [comment]
Hello:
How about trying to see this LIVE m3u8 link?
https://s0.usnlive.com/stream/cnn.m3u8
It is for US live news, it seems to be open for all people.

**Comment by zamgi** [comment]
403 Forbidden. ))))

**Comment by zydjohnHotmail** [comment]
Hello:
I found this M3U8 link:
https://rt-rtd.gcdn.co/live/rtdoc/playlist_2500Kb.m3u8
I think the official russian TV station should have some live M3U8 links now.
You can check their web site: www.rt.com

**Comment by zamgi** [comment]
hmm, it's a little more complicated: this link contain 10 segments by request, but if made request over little time (for example 1 sec.), content changed: the content will move several segments, or even the segments will be different. 
this probably means that for such links you need to request the next segments starting from some moment yourself ...

**Comment by zamgi** [comment]
here is the result of two requests from this link made a few seconds later:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:4125393
#EXTINF:2.00000,
playlist_2500Kb_4125393.ts
#EXTINF:2.00000,
playlist_2500Kb_4125394.ts
#EXTINF:2.00000,
playlist_2500Kb_4125395.ts
#EXTINF:2.00000,
playlist_2500Kb_4125396.ts
#EXTINF:2.00000,
playlist_2500Kb_4125397.ts
#EXTINF:2.00000,
playlist_2500Kb_4125398.ts
#EXTINF:2.00000,
playlist_2500Kb_4125399.ts
#EXTINF:2.00000,
playlist_2500Kb_4125400.ts
#EXTINF:2.00000,
playlist_2500Kb_4125401.ts
#EXTINF:2.00000,
playlist_2500Kb_4125402.ts

 patrs count: 10
-----------------------------------------------------

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:4125401
#EXTINF:2.00000,
playlist_2500Kb_4125401.ts
#EXTINF:2.00000,
playlist_2500Kb_4125402.ts
#EXTINF:2.00000,
playlist_2500Kb_4125403.ts
#EXTINF:2.00000,
playlist_2500Kb_4125404.ts
#EXTINF:2.00000,
playlist_2500Kb_4125405.ts
#EXTINF:2.00000,
playlist_2500Kb_4125406.ts
#EXTINF:2.00000,
playlist_2500Kb_4125407.ts
#EXTINF:2.00000,
playlist_2500Kb_4125408.ts
#EXTINF:2.00000,
playlist_2500Kb_4125409.ts
#EXTINF:2.00000,
playlist_2500Kb_4125410.ts

 patrs count: 10
-----------------------------------------------------

**Comment by zamgi** [comment]
for you information: Im created this tool for download movie, broadcasted over .m3u8 links. Im doesn't download live .m3u8 streaming - this not need for me.

**Comment by zydjohnHotmail** [comment]
Hello:
Form your testing, it seems your code can download live M3U8 links, right?
But need some more code to finish the job?
Can you do this and reload  the repo after finish?
Take your time, and much appreciated!
Thanks,

**Comment by zamgi** [comment]
I can't do this, because im doesn't have a time for this, because i'm working other job)))
this doesn't need personaly for me, sorry bro)))
you can try do this it yourself, it's not difficult, as it may seem))

**Comment by zamgi** [comment]
or find someone to do it for you and you pay him

**Comment by zydjohnHotmail** [comment]
OK, thanks!
